load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")

oncall("fill in oncall here @nocommit")

python_binary(
    name = "web_server",
    srcs = ["web_server.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.web_interface.web_server",
    deps = [
        "fbsource//third-party/pypi/flask:flask",
        "fbsource//third-party/pypi/numpy:numpy",
        "fbsource//third-party/pypi/psycopg2:psycopg2",
        "fbsource//third-party/pypi/sentence-transformers:sentence-transformers",
    ],
)

python_binary(
    name = "index",
    srcs = ["index.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.web_interface.index",
    deps = [
        "fbsource//third-party/pypi/flask:flask",
        "fbsource//third-party/pypi/psycopg2:psycopg2",
        "fbsource//third-party/pypi/pyyaml:pyyaml",
    ],
)

python_binary(
    name = "index",
    srcs = ["index.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.web_interface.index",
    deps = [
        "fbsource//third-party/pypi/flask:flask",
        "fbsource//third-party/pypi/psycopg2:psycopg2",
        "fbsource//third-party/pypi/pyyaml:pyyaml",
    ],
)
