"""
Shared pytest fixtures for Paper Agent tests.

This module provides common fixtures used across unit, integration, and e2e tests.
"""

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, Generator, List, Optional
from unittest.mock import MagicMock, patch

import pytest

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "paper_collection"))
sys.path.insert(0, str(PROJECT_ROOT / "paper_collection" / "paper_metadata"))
sys.path.insert(0, str(PROJECT_ROOT / "paper_collection" / "paper_summary"))
sys.path.insert(0, str(PROJECT_ROOT / "web_interface"))


# =============================================================================
# Test Data Paths
# =============================================================================

TEST_DATA_DIR = Path(__file__).parent / "test_data"


@pytest.fixture
def test_data_dir() -> Path:
    """Return path to test data directory."""
    return TEST_DATA_DIR


# =============================================================================
# Sample Data Fixtures
# =============================================================================


@pytest.fixture
def sample_scholar_html() -> str:
    """Sample Google Scholar alert email HTML."""
    return """
    <html>
    <body>
    <h3>Google Scholar Alert</h3>
    <a href="https://scholar.google.com/scholar_url?url=https://arxiv.org/abs/2401.12345">
        Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
    </a>
    <font color="#006621">A. Author, B. Researcher - arXiv, 2024</font>
    <div>This paper introduces a novel approach to RAG that combines dense retrieval
    with generative models for improved factuality and reduced hallucinations.</div>

    <a href="https://scholar.google.com/scholar_url?url=https://dl.acm.org/doi/10.1145/1234567">
        Memory-Augmented Neural Networks for Conversational AI
    </a>
    <font color="#006621">C. Developer, D. Engineer - ACM, 2024</font>
    <div>We present a memory-augmented architecture for long-context conversations.</div>
    </body>
    </html>
    """


@pytest.fixture
def sample_arxiv_html() -> str:
    """Sample ArXiv abstract page HTML."""
    return """
    <html>
    <head><title>arXiv:2401.12345</title></head>
    <body>
    <div class="submission-history">
        <strong>Submitted</strong> on 15 Jan 2024
    </div>
    <blockquote class="abstract">
        <span class="descriptor">Abstract:</span>
        This paper introduces a novel approach to retrieval-augmented generation (RAG)
        that combines dense retrieval with generative language models. Our method
        achieves state-of-the-art results on multiple knowledge-intensive benchmarks.
    </blockquote>
    </body>
    </html>
    """


@pytest.fixture
def sample_acm_html() -> str:
    """Sample ACM Digital Library page HTML."""
    return """
    <html>
    <head>
        <script type="application/ld+json">
        {"datePublished": "2024-05-15"}
        </script>
    </head>
    <body>
    <div class="abstractSection">
        <p>We present a memory-augmented neural network architecture designed for
        conversational AI systems with long-context understanding capabilities.</p>
    </div>
    </body>
    </html>
    """


@pytest.fixture
def sample_paper_dict() -> Dict[str, Any]:
    """Sample paper dictionary as returned by parser."""
    return {
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "authors": "A. Author, B. Researcher",
        "venue": "arXiv, 1/2024",
        "year": "2024",
        "snippet": "This paper introduces a novel approach to RAG...",
        "link": "https://arxiv.org/abs/2401.12345",
    }


@pytest.fixture
def sample_paper_db_row() -> Dict[str, Any]:
    """Sample paper as stored in database."""
    return {
        "id": 1,
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "authors": "A. Author, B. Researcher",
        "venue": "arXiv",
        "year": "2024",
        "abstract": "This paper introduces a novel approach to RAG...",
        "link": "https://arxiv.org/abs/2401.12345",
        "recomm_date": "2024-01-15",
        "topics": "RAG, Reasoning",
        "primary_topic": "RAG",
        "embedding": [0.1] * 512,
        "summary_generated_at": None,
        "summary_basics": None,
        "summary_core": None,
        "summary_techniques": None,
        "summary_experiments": None,
        "summary_figures": None,
    }


@pytest.fixture
def sample_summary_json() -> Dict[str, Any]:
    """Sample summary JSON as generated by LLM."""
    return {
        "basics": {
            "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
            "arxiv_id": "2401.12345",
            "venue": "arXiv",
            "year": "2024",
            "authors": ["A. Author", "B. Researcher"],
        },
        "core": {
            "topics": ["RAG", "Reasoning"],
            "primary_topic": "RAG",
            "sub_topic": "Dense Retrieval",
            "problem_statement": "Improving factuality in LLM outputs",
            "thesis": "Combining dense retrieval with generation improves accuracy",
            "novelty": "Novel retrieval-generation fusion mechanism",
            "breakthrough_score": 7,
        },
        "technical_details": {
            "pipeline": ["Retrieve relevant passages", "Generate with context"],
            "results": [{"metric": "Accuracy", "value": "85.3%", "baseline": "78.1%"}],
        },
        "experiments": {
            "pipeline": ["Retrieve relevant passages", "Generate with context"],
            "results": [{"metric": "Accuracy", "value": "85.3%", "baseline": "78.1%"}],
        },
    }


@pytest.fixture
def sample_topics_response() -> Dict[str, Any]:
    """Sample topic classification response from LLM."""
    return {
        "topics": ["RAG", "Reasoning"],
        "primary_topic": "RAG",
        "reasoning": "Paper focuses on retrieval-augmented generation techniques.",
    }


# =============================================================================
# Mock Fixtures
# =============================================================================


@pytest.fixture
def mock_gmail_service() -> MagicMock:
    """Mock Gmail API service."""
    service = MagicMock()

    # Mock messages list
    service.users().messages().list().execute.return_value = {
        "messages": [{"id": "msg123"}, {"id": "msg456"}]
    }

    # Mock message get
    service.users().messages().get().execute.return_value = {
        "id": "msg123",
        "payload": {
            "headers": [
                {"name": "From", "value": "scholaralerts-noreply@google.com"},
                {"name": "Subject", "value": "Google Scholar Alert"},
                {"name": "Date", "value": "Mon, 15 Jan 2024 10:00:00 -0800"},
            ],
            "body": {"data": ""},
            "parts": [
                {
                    "mimeType": "text/html",
                    "body": {"data": "PGh0bWw+PC9odG1sPg=="},  # base64 encoded
                }
            ],
        },
    }

    return service


@pytest.fixture
def mock_openai_embedding() -> List[float]:
    """Mock OpenAI embedding vector (512 dimensions)."""
    return [0.1] * 512


@pytest.fixture
def mock_gemini_response(sample_summary_json: Dict[str, Any]) -> Dict[str, Any]:
    """Mock Gemini API response."""
    return {"result": json.dumps(sample_summary_json)}


@pytest.fixture
def mock_db_connection() -> MagicMock:
    """Mock database connection."""
    conn = MagicMock()
    cursor = MagicMock()
    conn.cursor.return_value.__enter__ = MagicMock(return_value=cursor)
    conn.cursor.return_value.__exit__ = MagicMock(return_value=False)
    return conn


@pytest.fixture
def mock_paper_db(sample_paper_db_row: Dict[str, Any]) -> MagicMock:
    """Mock PaperDB instance."""
    db = MagicMock()
    db.get_paper_by_id.return_value = sample_paper_db_row
    db.get_all_papers.return_value = [sample_paper_db_row]
    db.add_paper.return_value = 1
    db.vector_search.return_value = [sample_paper_db_row]
    return db


# =============================================================================
# Configuration Fixtures
# =============================================================================


@pytest.fixture
def sample_config_dict() -> Dict[str, Any]:
    """Sample configuration dictionary."""
    return {
        "notification_email": "test@example.com",
        "website_url": "http://localhost:5001",
        "gmail": {
            "credentials_file": "credentials.json",
            "token_file": "token.json",
            "search_query": "from:scholaralerts-noreply@google.com",
        },
        "database": {
            "url": "postgresql://test:test@localhost:5432/test_papers",
        },
        "openai": {
            "api_key": "sk-test-key",
            "embedding_model": "text-embedding-3-small",
        },
        "gemini": {
            "api_key": "test-gemini-key",
            "api_url": "https://api.test.com/conversations/sync",
            "model": "gemini-2.0-flash",
            "lightweight_model": "gemini-2.0-flash-lite",
        },
        "web": {
            "host": "0.0.0.0",
            "port": 5001,
            "papers_per_page": 10,
        },
    }


@pytest.fixture
def temp_config_file(tmp_path: Path, sample_config_dict: Dict[str, Any]) -> Path:
    """Create a temporary config.yaml file."""
    import yaml

    config_file = tmp_path / "config.yaml"
    with open(config_file, "w") as f:
        yaml.dump(sample_config_dict, f)
    return config_file


# =============================================================================
# HTTP Mock Fixtures (for use with responses library)
# =============================================================================


@pytest.fixture
def mock_arxiv_request(sample_arxiv_html: str):
    """Setup mock for ArXiv HTTP requests."""
    try:
        import responses

        @responses.activate
        def _mock():
            responses.add(
                responses.GET,
                "https://arxiv.org/abs/2401.12345",
                body=sample_arxiv_html,
                status=200,
            )

        return _mock
    except ImportError:
        pytest.skip("responses library not installed")


@pytest.fixture
def mock_acm_request(sample_acm_html: str):
    """Setup mock for ACM HTTP requests."""
    try:
        import responses

        @responses.activate
        def _mock():
            responses.add(
                responses.GET,
                "https://dl.acm.org/doi/abs/10.1145/1234567",
                body=sample_acm_html,
                status=200,
            )

        return _mock
    except ImportError:
        pytest.skip("responses library not installed")


# =============================================================================
# Cleanup Fixtures
# =============================================================================


@pytest.fixture(autouse=True)
def reset_singletons():
    """Reset singleton instances between tests."""
    yield
    # Reset any global state here if needed


@pytest.fixture
def clean_env():
    """Temporarily clean environment variables."""
    original_env = os.environ.copy()
    # Remove potentially interfering env vars
    for key in ["GEMINI_API_KEY", "OPENAI_API_KEY", "DATABASE_URL"]:
        os.environ.pop(key, None)
    yield
    os.environ.clear()
    os.environ.update(original_env)


# =============================================================================
# Flask Test Client Fixtures
# =============================================================================


@pytest.fixture
def flask_app():
    """Create Flask app for testing."""
    try:
        from web_server import app

        app.config["TESTING"] = True
        return app
    except ImportError:
        pytest.skip("Flask app not available")


@pytest.fixture
def flask_client(flask_app):
    """Create Flask test client."""
    with flask_app.test_client() as client:
        yield client


# =============================================================================
# PDF Test Fixtures
# =============================================================================


@pytest.fixture
def sample_pdf_bytes() -> bytes:
    """Generate minimal valid PDF bytes for testing."""
    # Minimal PDF structure
    pdf_content = b"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>
endobj
4 0 obj
<< /Length 44 >>
stream
BT
/F1 12 Tf
100 700 Td
(Test PDF) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000206 00000 n
trailer
<< /Size 5 /Root 1 0 R >>
startxref
300
%%EOF"""
    return pdf_content


# =============================================================================
# Checkpoint Test Fixtures
# =============================================================================


@pytest.fixture
def temp_checkpoint_file(tmp_path: Path) -> Path:
    """Create a temporary checkpoint file path."""
    return tmp_path / "checkpoint.json"


@pytest.fixture
def sample_checkpoint_data() -> Dict[str, Any]:
    """Sample checkpoint data."""
    return {
        "started_at": "2024-01-15T10:00:00Z",
        "updated_at": "2024-01-15T12:00:00Z",
        "total_papers": 100,
        "all_ids": list(range(1, 101)),
        "completed_ids": [1, 2, 3, 4, 5],
        "failed_ids": [10, 20],
        "in_progress_id": 6,
        "errors": {
            "10": "HTTP 429: Rate limit exceeded",
            "20": "API call failed",
        },
        "abstract_only": {
            "15": "HTTP 404",
        },
    }
