load("@fbcode_macros//build_defs:python_library.bzl", "python_library")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")

oncall("fill in oncall here @nocommit")

python_binary(
    name = "paper_db",
    srcs = ["paper_db.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.paper_collection.paper_parse.paper_db",
)

python_binary(
    name = "arxiv_fetcher",
    srcs = ["arxiv_fetcher.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.paper_collection.paper_parse.arxiv_fetcher",
    deps = [
        "fbsource//third-party/pypi/requests:requests",
    ],
)

python_binary(
    name = "acm_fetcher",
    srcs = ["acm_fetcher.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.paper_collection.paper_parse.acm_fetcher",
    deps = [
        "fbsource//third-party/pypi/requests:requests",
    ],
)

python_binary(
    name = "topic_tagger",
    srcs = ["topic_tagger.py"],
    labels = ["autodeps2_generated"],
    main_module = "assistant.research.paper-agent.paper_collection.paper_parse.topic_tagger",
    deps = [],
)

python_library(
    name = "paper_parser",
    srcs = ["paper_parser.py"],
    labels = ["autodeps2_generated"],
)
